version: '3.8'

services:
  postgres_db:
    image: postgres:17
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - '5432:5432'
    networks:
      - prisma-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  server:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "4000:4000"
    env_file: ./backend/.env
    networks:
      - prisma-network
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes: 
      - ./backend:/app

  client:
    build:
      context: ./omakoju-front
      dockerfile: Dockerfile
    container_name: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    volumes:
      - ./omakoju-front:/app

  prisma-studio:
    image: node:lts-alpine3.17
    working_dir: /app
    volumes:
      - ./backend:/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    env_file:
      - ./backend/.env
    networks:
      - prisma-network
    depends_on:
      postgres_db:
        condition: service_healthy
      server:
        condition: service_started


networks:
  prisma-network:
    name: prisma-network

volumes:
  postgres_data: